### PR TITLE
Add XMEGA E5 support

### PR DESCRIPTION
**Pull request by nickdademo**

### CODE REVIEW

**Comment by cpavlina** [comment]
@alexforencich, I'm not sure if you're still working on xboot, but if so - I've tested this out, it works nicely. :)

**Comment by nickdademo** [comment]
Thanks for the update cpavlina! Did you have to make any changes at all?
I am using these modifications quite regularly in a commercial product also with no issues - I hope this PR gets merged soon :)

**Comment by alexforencich** [comment]
Needs a tabs/spaces fix, and has this been verified on non-E5 devices as well to ensure nothing is broken?  I will merge as soon as I get a chance to test it myself.

**Comment by cpavlina** [comment]
Nope, no changes.

I actually did all of the work myself before noticing there was a PR! :D Yours was almost line-for-line the same as mine...

**Comment by cpavlina** [comment]
@alexforencich - do you have access to an E5 series device to test it on? I just made up a few simple atxmega32e5 dev boards and still have a spare, I could mail you one if you like.

**Comment by alexforencich** [comment]
If you have an extra board, that would be great!  Please send me an email directly.

**Comment by cpavlina** [comment]
@nickdademo - might I suggest a simple change? xboot.c is already looking pretty long and twisted - I could hardly stop myself from beginning to refactor that ;) - when I was doing my version, I found that the UART_REMAP bit fit more nicely into uart_init() and uart_deinit() inside uart.c, as that is where all of the UART pin configuration is done, rather than adding another block in xboot.c.

**Comment by nickdademo** [comment]
Sounds good to me! Are you able commit this change? I guess you'll have to fork my fork.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        From: Chris PavlinaSent: Tuesday, 15 September 2015 10:08 PMTo: alexforencich/xbootReply To: alexforencich/xbootCc: nickdademoSubject: Re: [xboot] Add XMEGA E5 support (#17)@nickdademo - might I suggest a simple change? xboot.c is already looking pretty long and twisted - I could hardly stop myself from beginning to refactor that ;) - when I was doing my version, I found that the UART_REMAP bit fit more nicely into uart_init() and uart_deinit() inside uart.c, as that is where all of the UART pin configuration is done, rather than adding another block in xboot.c.

—Reply to this email directly or view it on GitHub.

**Comment by cpavlina** [comment]
I can commit it myself if you like - you're right, I'll have to fork your fork and then you can merge my pull so Alex can merge your pull with my pull (yo dawg...)

**Comment by alexforencich** [comment]
Just finished testing this on atxmega64a3, atmega328p, and atxmega32e5 (thanks @cpavlina for the e5 board).  Main bootloader functions work, API is accessible.

**Pull request merged**
